spring:
  application:
    name: webjtime
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

vaadin:
  launch-browser: false
