spring:
  application:
    name: webjtime
  datasource:
    url: jdbc:h2:file:./file/125587db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
Vaadin:
  launch-browser: true
